test_lua53:
    stage: test
    image: registry.gitlab.com/thislight/hussar:alpine3d12_lua53
    script:
        - luarocks make
        - /bin/busted

test_lua54:
    stage: test
    image: registry.gitlab.com/thislight/hussar:alpine3d12_lua54
    script:
        - luarocks make
        - /bin/busted