test_lua53:
    stage: test
    image: registry.gitlab.com/thislight/hussar:f32_l53
    script:
        - luarocks make
        - /bin/busted

test_lua54:
    stage: test
    image: rregistry.gitlab.com/thislight/hussar:f33_l54
    script:
        - luarocks make
        - /bin/busted